// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for Common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxDb21tb24ucHJvdG8SCFByb3RvY29sIjcKCUxvZ2luRGF0YRIMCgRtYWls",
            "GAEgASgJEgoKAmlkGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJKvoICg1QQUNL",
            "RVRfSEVBREVSEg8KC1BLVF9VTktOT1dOEAASEQoNUEtUX0hBTkRTSEFLRRAB",
            "EhMKDVBLVF9SRVFfTE9HSU4QqYw9EhUKD1BLVF9SRVFfU0lHTl9VUBCRlD0S",
            "GgoUUEtUX1JFUV9TSUdOX1VQX0FVVEgQkpQ9EhsKFVBLVF9SRVFfQUNDX1VQ",
            "REFURV9JRBD5mz0SGwoVUEtUX1JFUV9BQ0NfVVBEQVRFX1BXEPqbPRIdChdQ",
            "S1RfUkVRX0FDQ19VUERBVEVfQVVUSBD7mz0SHAoWUEtUX1JFUV9DTk5fTE9C",
            "QllfU0VSVhDhoz0SGwoVUEtUX1JFUV9DTk5fR0FNRV9TRVJWEOKjPRIbChVQ",
            "S1RfUkVRX0NOTl9DSEFUX1NFUlYQ46M9EhoKFFBLVF9SRVFfRENfQVVUSF9T",
            "RVJWEMmrPRIbChVQS1RfUkVRX0RDX0xPQkJZX1NFUlYQyqs9EhoKFFBLVF9S",
            "RVFfRENfR0FNRV9TRVJWEMurPRIaChRQS1RfUkVRX0RDX0NIQVRfU0VSVhDM",
            "qz0SHAoWUEtUX0ZBSUxfTE9HSU5fVU5LTk9XThDJmUMSHQoXUEtUX0ZBSUxf",
            "TE9HSU5fSU5WX01BSUwQyplDEhsKFVBLVF9GQUlMX0xPR0lOX0lOVl9JRBDL",
            "mUMSGwoVUEtUX0ZBSUxfTE9HSU5fSU5WX1BXEMyZQxIYChJQS1RfRkFJTF9M",
            "T0dJTl9CQU4QzZlDEh4KGFBLVF9GQUlMX1NJR05fVVBfVU5LTk9XThCxoUMS",
            "HwoZUEtUX0ZBSUxfU0lHTl9VUF9JTlZfTUFJTBCyoUMSHwoZUEtUX0ZBSUxf",
            "U0lHTl9VUF9NQUlMX0JBThCzoUMSHQoXUEtUX0ZBSUxfU0lHTl9VUF9EVVBf",
            "SUQQtKFDEh0KF1BLVF9GQUlMX1NJR05fVVBfSU5WX1BXELWhQxIfChlQS1Rf",
            "RkFJTF9TSUdOX1VQX0lOVl9BVVRIELahQxIcChZQS1RfRkFJTF9BQ0NfVVBE",
            "QVRFX0lEEJmpQxIcChZQS1RfRkFJTF9BQ0NfVVBEQVRFX1BXEJqpQxIeChhQ",
            "S1RfRkFJTF9BQ0NfVVBEQVRFX0FVVEgQm6lDEhwKFlBLVF9GQUlMX0NOTl9B",
            "VVRIX1NFUlYQgbFDEh0KF1BLVF9GQUlMX0NOTl9MT0JCWV9TRVJWEIKxQxIc",
            "ChZQS1RfRkFJTF9DTk5fR0FNRV9TRVJWEIOxQxIcChZQS1RfRkFJTF9DTk5f",
            "Q0hBVF9TRVJWEISxQxITCg1QS1RfU1VDX0xPR0lOEOmmSRIVCg9QS1RfU1VD",
            "X1NJR05fVVAQ0a5JEhgKElBLVF9TVUNfU0lHTl9VUF9JRBDSrkkSGAoSUEtU",
            "X1NVQ19TSUdOX1VQX1BXENOuSRIaChRQS1RfU1VDX1NJR05fVVBfQVVUSBDU",
            "rkkSGwoVUEtUX1NVQ19BQ0NfVVBEQVRFX0lEELm2SRIbChVQS1RfU1VDX0FD",
            "Q19VUERBVEVfUFcQurZJKh0KCkVSUk9SX0NPREUSDwoLRVJSX1VOS05PV04Q",
            "AGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.PACKET_HEADER), typeof(global::Protocol.ERROR_CODE), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.LoginData), global::Protocol.LoginData.Parser, new[]{ "Mail", "Id", "Password" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PACKET_HEADER {
    [pbr::OriginalName("PKT_UNKNOWN")] PktUnknown = 0,
    [pbr::OriginalName("PKT_HANDSHAKE")] PktHandshake = 1,
    /// <summary>
    ///PKT_REQ_LOGIN
    /// </summary>
    [pbr::OriginalName("PKT_REQ_LOGIN")] PktReqLogin = 1001001,
    /// <summary>
    ///PKT_REQ_SIGN_UP
    /// </summary>
    [pbr::OriginalName("PKT_REQ_SIGN_UP")] PktReqSignUp = 1002001,
    [pbr::OriginalName("PKT_REQ_SIGN_UP_AUTH")] PktReqSignUpAuth = 1002002,
    /// <summary>
    ///PKT_REQ_ACC_UPDATE
    /// </summary>
    [pbr::OriginalName("PKT_REQ_ACC_UPDATE_ID")] PktReqAccUpdateId = 1003001,
    [pbr::OriginalName("PKT_REQ_ACC_UPDATE_PW")] PktReqAccUpdatePw = 1003002,
    [pbr::OriginalName("PKT_REQ_ACC_UPDATE_AUTH")] PktReqAccUpdateAuth = 1003003,
    /// <summary>
    ///PKT_REQ_CNN
    /// </summary>
    [pbr::OriginalName("PKT_REQ_CNN_LOBBY_SERV")] PktReqCnnLobbyServ = 1004001,
    [pbr::OriginalName("PKT_REQ_CNN_GAME_SERV")] PktReqCnnGameServ = 1004002,
    [pbr::OriginalName("PKT_REQ_CNN_CHAT_SERV")] PktReqCnnChatServ = 1004003,
    /// <summary>
    ///PKT_REQ_DC
    /// </summary>
    [pbr::OriginalName("PKT_REQ_DC_AUTH_SERV")] PktReqDcAuthServ = 1005001,
    [pbr::OriginalName("PKT_REQ_DC_LOBBY_SERV")] PktReqDcLobbyServ = 1005002,
    [pbr::OriginalName("PKT_REQ_DC_GAME_SERV")] PktReqDcGameServ = 1005003,
    [pbr::OriginalName("PKT_REQ_DC_CHAT_SERV")] PktReqDcChatServ = 1005004,
    /// <summary>
    ///PKT_FAIL_LOGIN
    /// </summary>
    [pbr::OriginalName("PKT_FAIL_LOGIN_UNKNOWN")] PktFailLoginUnknown = 1101001,
    [pbr::OriginalName("PKT_FAIL_LOGIN_INV_MAIL")] PktFailLoginInvMail = 1101002,
    [pbr::OriginalName("PKT_FAIL_LOGIN_INV_ID")] PktFailLoginInvId = 1101003,
    [pbr::OriginalName("PKT_FAIL_LOGIN_INV_PW")] PktFailLoginInvPw = 1101004,
    [pbr::OriginalName("PKT_FAIL_LOGIN_BAN")] PktFailLoginBan = 1101005,
    /// <summary>
    ///PKT_FAIL_SIGN_UP
    /// </summary>
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_UNKNOWN")] PktFailSignUpUnknown = 1102001,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_INV_MAIL")] PktFailSignUpInvMail = 1102002,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_MAIL_BAN")] PktFailSignUpMailBan = 1102003,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_DUP_ID")] PktFailSignUpDupId = 1102004,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_INV_PW")] PktFailSignUpInvPw = 1102005,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_INV_AUTH")] PktFailSignUpInvAuth = 1102006,
    /// <summary>
    ///PKT_FAIL_ACC_UPDATE
    /// </summary>
    [pbr::OriginalName("PKT_FAIL_ACC_UPDATE_ID")] PktFailAccUpdateId = 1103001,
    [pbr::OriginalName("PKT_FAIL_ACC_UPDATE_PW")] PktFailAccUpdatePw = 1103002,
    [pbr::OriginalName("PKT_FAIL_ACC_UPDATE_AUTH")] PktFailAccUpdateAuth = 1103003,
    /// <summary>
    ///PKT_FAIL_CONNECT
    /// </summary>
    [pbr::OriginalName("PKT_FAIL_CNN_AUTH_SERV")] PktFailCnnAuthServ = 1104001,
    [pbr::OriginalName("PKT_FAIL_CNN_LOBBY_SERV")] PktFailCnnLobbyServ = 1104002,
    [pbr::OriginalName("PKT_FAIL_CNN_GAME_SERV")] PktFailCnnGameServ = 1104003,
    [pbr::OriginalName("PKT_FAIL_CNN_CHAT_SERV")] PktFailCnnChatServ = 1104004,
    /// <summary>
    ///PKT_SUC_LOGIN
    /// </summary>
    [pbr::OriginalName("PKT_SUC_LOGIN")] PktSucLogin = 1201001,
    /// <summary>
    ///PKT_SUC_SIGN_UP
    /// </summary>
    [pbr::OriginalName("PKT_SUC_SIGN_UP")] PktSucSignUp = 1202001,
    [pbr::OriginalName("PKT_SUC_SIGN_UP_ID")] PktSucSignUpId = 1202002,
    [pbr::OriginalName("PKT_SUC_SIGN_UP_PW")] PktSucSignUpPw = 1202003,
    [pbr::OriginalName("PKT_SUC_SIGN_UP_AUTH")] PktSucSignUpAuth = 1202004,
    /// <summary>
    ///PKT_SUC_ACC_UPDATE
    /// </summary>
    [pbr::OriginalName("PKT_SUC_ACC_UPDATE_ID")] PktSucAccUpdateId = 1203001,
    [pbr::OriginalName("PKT_SUC_ACC_UPDATE_PW")] PktSucAccUpdatePw = 1203002,
  }

  public enum ERROR_CODE {
    [pbr::OriginalName("ERR_UNKNOWN")] ErrUnknown = 0,
  }

  #endregion

  #region Messages
  public sealed partial class LoginData : pb::IMessage<LoginData> {
    private static readonly pb::MessageParser<LoginData> _parser = new pb::MessageParser<LoginData>(() => new LoginData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginData(LoginData other) : this() {
      mail_ = other.mail_;
      id_ = other.id_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginData Clone() {
      return new LoginData(this);
    }

    /// <summary>Field number for the "mail" field.</summary>
    public const int MailFieldNumber = 1;
    private string mail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mail {
      get { return mail_; }
      set {
        mail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mail != other.Mail) return false;
      if (Id != other.Id) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mail.Length != 0) hash ^= Mail.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mail.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mail);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mail);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginData other) {
      if (other == null) {
        return;
      }
      if (other.Mail.Length != 0) {
        Mail = other.Mail;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mail = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
