// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for Common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxDb21tb24ucHJvdG8SCFByb3RvY29sIjcKCUxvZ2luRGF0YRIMCgRtYWls",
            "GAEgASgJEgoKAmlkGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJKs0ICg1QQUNL",
            "RVRfSEVBREVSEg8KC1BLVF9VTktOT1dOEAASEwoNUEtUX1JFUV9MT0dJThCp",
            "jD0SFQoPUEtUX1JFUV9TSUdOX1VQEJGUPRIaChRQS1RfUkVRX1NJR05fVVBf",
            "QVVUSBCSlD0SHQoXUEtUX1JFUV9HTUFJTF9TRU5EX0FVVEgQ+Zs9Eh0KF1BL",
            "VF9SRVFfQUNDX1VQREFURV9OQU1FEOGjPRIbChVQS1RfUkVRX0FDQ19VUERB",
            "VEVfUFcQ4qM9EhwKFlBLVF9SRVFfQ05OX0xPQkJZX1NFUlYQyas9EhsKFVBL",
            "VF9SRVFfQ05OX0dBTUVfU0VSVhDKqz0SGwoVUEtUX1JFUV9DTk5fQ0hBVF9T",
            "RVJWEMurPRIaChRQS1RfUkVRX0RDX0FVVEhfU0VSVhCxsz0SGwoVUEtUX1JF",
            "UV9EQ19MT0JCWV9TRVJWELKzPRIaChRQS1RfUkVRX0RDX0dBTUVfU0VSVhCz",
            "sz0SGgoUUEtUX1JFUV9EQ19DSEFUX1NFUlYQtLM9EhwKFlBLVF9GQUlMX0xP",
            "R0lOX1VOS05PV04QyZlDEh0KF1BLVF9GQUlMX0xPR0lOX0lOVl9NQUlMEMqZ",
            "QxIbChVQS1RfRkFJTF9MT0dJTl9JTlZfSUQQy5lDEhsKFVBLVF9GQUlMX0xP",
            "R0lOX0lOVl9QVxDMmUMSGAoSUEtUX0ZBSUxfTE9HSU5fQkFOEM2ZQxIeChhQ",
            "S1RfRkFJTF9TSUdOX1VQX1VOS05PV04QsaFDEh8KGVBLVF9GQUlMX1NJR05f",
            "VVBfSU5WX01BSUwQsqFDEh8KGVBLVF9GQUlMX1NJR05fVVBfTUFJTF9CQU4Q",
            "s6FDEh0KF1BLVF9GQUlMX1NJR05fVVBfRFVQX0lEELShQxIdChdQS1RfRkFJ",
            "TF9TSUdOX1VQX0lOVl9QVxC1oUMSHwoZUEtUX0ZBSUxfU0lHTl9VUF9JTlZf",
            "QVVUSBC2oUMSHgoYUEtUX0ZBSUxfQUNDX1VQREFURV9OQU1FEJmpQxIcChZQ",
            "S1RfRkFJTF9BQ0NfVVBEQVRFX1BXEJqpQxIcChZQS1RfRkFJTF9DTk5fQVVU",
            "SF9TRVJWEIGxQxIdChdQS1RfRkFJTF9DTk5fTE9CQllfU0VSVhCCsUMSHAoW",
            "UEtUX0ZBSUxfQ05OX0dBTUVfU0VSVhCDsUMSHAoWUEtUX0ZBSUxfQ05OX0NI",
            "QVRfU0VSVhCEsUMSEwoNUEtUX1NVQ19MT0dJThDppkkSFQoPUEtUX1NVQ19T",
            "SUdOX1VQENGuSRIYChJQS1RfU1VDX1NJR05fVVBfSUQQ0q5JEhgKElBLVF9T",
            "VUNfU0lHTl9VUF9QVxDTrkkSGgoUUEtUX1NVQ19TSUdOX1VQX0FVVEgQ1K5J",
            "Eh0KF1BLVF9TVUNfQUNDX1VQREFURV9OQU1FELm2SRIbChVQS1RfU1VDX0FD",
            "Q19VUERBVEVfUFcQurZJKh0KCkVSUk9SX0NPREUSDwoLRVJSX1VOS05PV04Q",
            "AGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.PACKET_HEADER), typeof(global::Protocol.ERROR_CODE), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.LoginData), global::Protocol.LoginData.Parser, new[]{ "Mail", "Id", "Password" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PACKET_HEADER {
    [pbr::OriginalName("PKT_UNKNOWN")] PktUnknown = 0,
    /// <summary>
    ///PKT_REQ_LOGIN
    /// </summary>
    [pbr::OriginalName("PKT_REQ_LOGIN")] PktReqLogin = 1001001,
    /// <summary>
    ///PKT_REQ_SIGN_UP
    /// </summary>
    [pbr::OriginalName("PKT_REQ_SIGN_UP")] PktReqSignUp = 1002001,
    [pbr::OriginalName("PKT_REQ_SIGN_UP_AUTH")] PktReqSignUpAuth = 1002002,
    /// <summary>
    ///PKT_REQ_GMAIL
    /// </summary>
    [pbr::OriginalName("PKT_REQ_GMAIL_SEND_AUTH")] PktReqGmailSendAuth = 1003001,
    /// <summary>
    ///PKT_REQ_ACC_UPDATE
    /// </summary>
    [pbr::OriginalName("PKT_REQ_ACC_UPDATE_NAME")] PktReqAccUpdateName = 1004001,
    [pbr::OriginalName("PKT_REQ_ACC_UPDATE_PW")] PktReqAccUpdatePw = 1004002,
    /// <summary>
    ///PKT_REQ_CNN
    /// </summary>
    [pbr::OriginalName("PKT_REQ_CNN_LOBBY_SERV")] PktReqCnnLobbyServ = 1005001,
    [pbr::OriginalName("PKT_REQ_CNN_GAME_SERV")] PktReqCnnGameServ = 1005002,
    [pbr::OriginalName("PKT_REQ_CNN_CHAT_SERV")] PktReqCnnChatServ = 1005003,
    /// <summary>
    ///PKT_REQ_DC
    /// </summary>
    [pbr::OriginalName("PKT_REQ_DC_AUTH_SERV")] PktReqDcAuthServ = 1006001,
    [pbr::OriginalName("PKT_REQ_DC_LOBBY_SERV")] PktReqDcLobbyServ = 1006002,
    [pbr::OriginalName("PKT_REQ_DC_GAME_SERV")] PktReqDcGameServ = 1006003,
    [pbr::OriginalName("PKT_REQ_DC_CHAT_SERV")] PktReqDcChatServ = 1006004,
    /// <summary>
    ///PKT_FAIL_LOGIN
    /// </summary>
    [pbr::OriginalName("PKT_FAIL_LOGIN_UNKNOWN")] PktFailLoginUnknown = 1101001,
    [pbr::OriginalName("PKT_FAIL_LOGIN_INV_MAIL")] PktFailLoginInvMail = 1101002,
    [pbr::OriginalName("PKT_FAIL_LOGIN_INV_ID")] PktFailLoginInvId = 1101003,
    [pbr::OriginalName("PKT_FAIL_LOGIN_INV_PW")] PktFailLoginInvPw = 1101004,
    [pbr::OriginalName("PKT_FAIL_LOGIN_BAN")] PktFailLoginBan = 1101005,
    /// <summary>
    ///PKT_FAIL_SIGN_UP
    /// </summary>
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_UNKNOWN")] PktFailSignUpUnknown = 1102001,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_INV_MAIL")] PktFailSignUpInvMail = 1102002,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_MAIL_BAN")] PktFailSignUpMailBan = 1102003,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_DUP_ID")] PktFailSignUpDupId = 1102004,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_INV_PW")] PktFailSignUpInvPw = 1102005,
    [pbr::OriginalName("PKT_FAIL_SIGN_UP_INV_AUTH")] PktFailSignUpInvAuth = 1102006,
    /// <summary>
    ///PKT_FAIL_ACC_UPDATE
    /// </summary>
    [pbr::OriginalName("PKT_FAIL_ACC_UPDATE_NAME")] PktFailAccUpdateName = 1103001,
    [pbr::OriginalName("PKT_FAIL_ACC_UPDATE_PW")] PktFailAccUpdatePw = 1103002,
    /// <summary>
    ///PKT_FAIL_CONNECT
    /// </summary>
    [pbr::OriginalName("PKT_FAIL_CNN_AUTH_SERV")] PktFailCnnAuthServ = 1104001,
    [pbr::OriginalName("PKT_FAIL_CNN_LOBBY_SERV")] PktFailCnnLobbyServ = 1104002,
    [pbr::OriginalName("PKT_FAIL_CNN_GAME_SERV")] PktFailCnnGameServ = 1104003,
    [pbr::OriginalName("PKT_FAIL_CNN_CHAT_SERV")] PktFailCnnChatServ = 1104004,
    /// <summary>
    ///PKT_SUC_LOGIN
    /// </summary>
    [pbr::OriginalName("PKT_SUC_LOGIN")] PktSucLogin = 1201001,
    /// <summary>
    ///PKT_SUC_SIGN_UP
    /// </summary>
    [pbr::OriginalName("PKT_SUC_SIGN_UP")] PktSucSignUp = 1202001,
    [pbr::OriginalName("PKT_SUC_SIGN_UP_ID")] PktSucSignUpId = 1202002,
    [pbr::OriginalName("PKT_SUC_SIGN_UP_PW")] PktSucSignUpPw = 1202003,
    [pbr::OriginalName("PKT_SUC_SIGN_UP_AUTH")] PktSucSignUpAuth = 1202004,
    /// <summary>
    ///PKT_SUC_ACC_UPDATE
    /// </summary>
    [pbr::OriginalName("PKT_SUC_ACC_UPDATE_NAME")] PktSucAccUpdateName = 1203001,
    [pbr::OriginalName("PKT_SUC_ACC_UPDATE_PW")] PktSucAccUpdatePw = 1203002,
  }

  public enum ERROR_CODE {
    [pbr::OriginalName("ERR_UNKNOWN")] ErrUnknown = 0,
  }

  #endregion

  #region Messages
  public sealed partial class LoginData : pb::IMessage<LoginData> {
    private static readonly pb::MessageParser<LoginData> _parser = new pb::MessageParser<LoginData>(() => new LoginData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginData(LoginData other) : this() {
      mail_ = other.mail_;
      id_ = other.id_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginData Clone() {
      return new LoginData(this);
    }

    /// <summary>Field number for the "mail" field.</summary>
    public const int MailFieldNumber = 1;
    private string mail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mail {
      get { return mail_; }
      set {
        mail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mail != other.Mail) return false;
      if (Id != other.Id) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mail.Length != 0) hash ^= Mail.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mail.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mail);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mail);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginData other) {
      if (other == null) {
        return;
      }
      if (other.Mail.Length != 0) {
        Mail = other.Mail;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mail = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
