// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Common_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Common_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Common_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Common_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Common_2eproto;
namespace Protocol {
class LoginData;
class LoginDataDefaultTypeInternal;
extern LoginDataDefaultTypeInternal _LoginData_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::LoginData* Arena::CreateMaybeMessage<::Protocol::LoginData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum PACKET_HEADER : int {
  PKT_UNKNOWN = 0,
  PKT_HANDSHAKE = 1,
  PKT_REQ_LOGIN = 1001001,
  PKT_REQ_SIGN_UP = 1002001,
  PKT_REQ_SIGN_UP_AUTH = 1002002,
  PKT_REQ_ACC_UPDATE_ID = 1003001,
  PKT_REQ_ACC_UPDATE_PW = 1003002,
  PKT_REQ_ACC_UPDATE_AUTH = 1003003,
  PKT_REQ_CNN_LOBBY_SERV = 1004001,
  PKT_REQ_CNN_GAME_SERV = 1004002,
  PKT_REQ_CNN_CHAT_SERV = 1004003,
  PKT_REQ_DC_AUTH_SERV = 1005001,
  PKT_REQ_DC_LOBBY_SERV = 1005002,
  PKT_REQ_DC_GAME_SERV = 1005003,
  PKT_REQ_DC_CHAT_SERV = 1005004,
  PKT_FAIL_LOGIN_UNKNOWN = 1101001,
  PKT_FAIL_LOGIN_INV_MAIL = 1101002,
  PKT_FAIL_LOGIN_INV_ID = 1101003,
  PKT_FAIL_LOGIN_INV_PW = 1101004,
  PKT_FAIL_LOGIN_BAN = 1101005,
  PKT_FAIL_SIGN_UP_UNKNOWN = 1102001,
  PKT_FAIL_SIGN_UP_INV_MAIL = 1102002,
  PKT_FAIL_SIGN_UP_MAIL_BAN = 1102003,
  PKT_FAIL_SIGN_UP_DUP_ID = 1102004,
  PKT_FAIL_SIGN_UP_INV_PW = 1102005,
  PKT_FAIL_SIGN_UP_INV_AUTH = 1102006,
  PKT_FAIL_ACC_UPDATE_ID = 1103001,
  PKT_FAIL_ACC_UPDATE_PW = 1103002,
  PKT_FAIL_ACC_UPDATE_AUTH = 1103003,
  PKT_FAIL_CNN_AUTH_SERV = 1104001,
  PKT_FAIL_CNN_LOBBY_SERV = 1104002,
  PKT_FAIL_CNN_GAME_SERV = 1104003,
  PKT_FAIL_CNN_CHAT_SERV = 1104004,
  PKT_SUC_LOGIN = 1201001,
  PKT_SUC_SIGN_UP = 1202001,
  PKT_SUC_SIGN_UP_ID = 1202002,
  PKT_SUC_SIGN_UP_PW = 1202003,
  PKT_SUC_SIGN_UP_AUTH = 1202004,
  PKT_SUC_ACC_UPDATE_ID = 1203001,
  PKT_SUC_ACC_UPDATE_PW = 1203002,
  PACKET_HEADER_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PACKET_HEADER_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PACKET_HEADER_IsValid(int value);
constexpr PACKET_HEADER PACKET_HEADER_MIN = PKT_UNKNOWN;
constexpr PACKET_HEADER PACKET_HEADER_MAX = PKT_SUC_ACC_UPDATE_PW;
constexpr int PACKET_HEADER_ARRAYSIZE = PACKET_HEADER_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PACKET_HEADER_descriptor();
template<typename T>
inline const std::string& PACKET_HEADER_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PACKET_HEADER>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PACKET_HEADER_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PACKET_HEADER_descriptor(), enum_t_value);
}
inline bool PACKET_HEADER_Parse(
    const std::string& name, PACKET_HEADER* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PACKET_HEADER>(
    PACKET_HEADER_descriptor(), name, value);
}
enum ERROR_CODE : int {
  ERR_UNKNOWN = 0,
  ERROR_CODE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ERROR_CODE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ERROR_CODE_IsValid(int value);
constexpr ERROR_CODE ERROR_CODE_MIN = ERR_UNKNOWN;
constexpr ERROR_CODE ERROR_CODE_MAX = ERR_UNKNOWN;
constexpr int ERROR_CODE_ARRAYSIZE = ERROR_CODE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ERROR_CODE_descriptor();
template<typename T>
inline const std::string& ERROR_CODE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ERROR_CODE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ERROR_CODE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ERROR_CODE_descriptor(), enum_t_value);
}
inline bool ERROR_CODE_Parse(
    const std::string& name, ERROR_CODE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ERROR_CODE>(
    ERROR_CODE_descriptor(), name, value);
}
// ===================================================================

class LoginData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.LoginData) */ {
 public:
  LoginData();
  virtual ~LoginData();

  LoginData(const LoginData& from);
  LoginData(LoginData&& from) noexcept
    : LoginData() {
    *this = ::std::move(from);
  }

  inline LoginData& operator=(const LoginData& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginData& operator=(LoginData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LoginData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoginData* internal_default_instance() {
    return reinterpret_cast<const LoginData*>(
               &_LoginData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LoginData& a, LoginData& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginData* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoginData* New() const final {
    return CreateMaybeMessage<LoginData>(nullptr);
  }

  LoginData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoginData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoginData& from);
  void MergeFrom(const LoginData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.LoginData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Common_2eproto);
    return ::descriptor_table_Common_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMailFieldNumber = 1,
    kIdFieldNumber = 2,
    kPasswordFieldNumber = 3,
  };
  // string mail = 1;
  void clear_mail();
  const std::string& mail() const;
  void set_mail(const std::string& value);
  void set_mail(std::string&& value);
  void set_mail(const char* value);
  void set_mail(const char* value, size_t size);
  std::string* mutable_mail();
  std::string* release_mail();
  void set_allocated_mail(std::string* mail);
  private:
  const std::string& _internal_mail() const;
  void _internal_set_mail(const std::string& value);
  std::string* _internal_mutable_mail();
  public:

  // string id = 2;
  void clear_id();
  const std::string& id() const;
  void set_id(const std::string& value);
  void set_id(std::string&& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  std::string* mutable_id();
  std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string password = 3;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.LoginData)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mail_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Common_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LoginData

// string mail = 1;
inline void LoginData::clear_mail() {
  mail_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& LoginData::mail() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginData.mail)
  return _internal_mail();
}
inline void LoginData::set_mail(const std::string& value) {
  _internal_set_mail(value);
  // @@protoc_insertion_point(field_set:Protocol.LoginData.mail)
}
inline std::string* LoginData::mutable_mail() {
  // @@protoc_insertion_point(field_mutable:Protocol.LoginData.mail)
  return _internal_mutable_mail();
}
inline const std::string& LoginData::_internal_mail() const {
  return mail_.GetNoArena();
}
inline void LoginData::_internal_set_mail(const std::string& value) {
  
  mail_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void LoginData::set_mail(std::string&& value) {
  
  mail_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Protocol.LoginData.mail)
}
inline void LoginData::set_mail(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mail_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Protocol.LoginData.mail)
}
inline void LoginData::set_mail(const char* value, size_t size) {
  
  mail_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Protocol.LoginData.mail)
}
inline std::string* LoginData::_internal_mutable_mail() {
  
  return mail_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* LoginData::release_mail() {
  // @@protoc_insertion_point(field_release:Protocol.LoginData.mail)
  
  return mail_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void LoginData::set_allocated_mail(std::string* mail) {
  if (mail != nullptr) {
    
  } else {
    
  }
  mail_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mail);
  // @@protoc_insertion_point(field_set_allocated:Protocol.LoginData.mail)
}

// string id = 2;
inline void LoginData::clear_id() {
  id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& LoginData::id() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginData.id)
  return _internal_id();
}
inline void LoginData::set_id(const std::string& value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.LoginData.id)
}
inline std::string* LoginData::mutable_id() {
  // @@protoc_insertion_point(field_mutable:Protocol.LoginData.id)
  return _internal_mutable_id();
}
inline const std::string& LoginData::_internal_id() const {
  return id_.GetNoArena();
}
inline void LoginData::_internal_set_id(const std::string& value) {
  
  id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void LoginData::set_id(std::string&& value) {
  
  id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Protocol.LoginData.id)
}
inline void LoginData::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Protocol.LoginData.id)
}
inline void LoginData::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Protocol.LoginData.id)
}
inline std::string* LoginData::_internal_mutable_id() {
  
  return id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* LoginData::release_id() {
  // @@protoc_insertion_point(field_release:Protocol.LoginData.id)
  
  return id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void LoginData::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:Protocol.LoginData.id)
}

// string password = 3;
inline void LoginData::clear_password() {
  password_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& LoginData::password() const {
  // @@protoc_insertion_point(field_get:Protocol.LoginData.password)
  return _internal_password();
}
inline void LoginData::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:Protocol.LoginData.password)
}
inline std::string* LoginData::mutable_password() {
  // @@protoc_insertion_point(field_mutable:Protocol.LoginData.password)
  return _internal_mutable_password();
}
inline const std::string& LoginData::_internal_password() const {
  return password_.GetNoArena();
}
inline void LoginData::_internal_set_password(const std::string& value) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void LoginData::set_password(std::string&& value) {
  
  password_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Protocol.LoginData.password)
}
inline void LoginData::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Protocol.LoginData.password)
}
inline void LoginData::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Protocol.LoginData.password)
}
inline std::string* LoginData::_internal_mutable_password() {
  
  return password_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* LoginData::release_password() {
  // @@protoc_insertion_point(field_release:Protocol.LoginData.password)
  
  return password_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void LoginData::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:Protocol.LoginData.password)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::PACKET_HEADER> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::PACKET_HEADER>() {
  return ::Protocol::PACKET_HEADER_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ERROR_CODE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ERROR_CODE>() {
  return ::Protocol::ERROR_CODE_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Common_2eproto
