// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

#include "Common.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Protocol {
class LoginDataDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LoginData> _instance;
} _LoginData_default_instance_;
}  // namespace Protocol
static void InitDefaultsscc_info_LoginData_Common_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Protocol::_LoginData_default_instance_;
    new (ptr) ::Protocol::LoginData();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Protocol::LoginData::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LoginData_Common_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_LoginData_Common_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Common_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_Common_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Common_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Common_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginData, mail_),
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginData, id_),
  PROTOBUF_FIELD_OFFSET(::Protocol::LoginData, password_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Protocol::LoginData)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Protocol::_LoginData_default_instance_),
};

const char descriptor_table_protodef_Common_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Common.proto\022\010Protocol\"7\n\tLoginData\022\014\n"
  "\004mail\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\020\n\010password\030\003 \001("
  "\t*\372\010\n\rPACKET_HEADER\022\017\n\013PKT_UNKNOWN\020\000\022\021\n\r"
  "PKT_HANDSHAKE\020\001\022\023\n\rPKT_REQ_LOGIN\020\251\214=\022\025\n\017"
  "PKT_REQ_SIGN_UP\020\221\224=\022\032\n\024PKT_REQ_SIGN_UP_A"
  "UTH\020\222\224=\022\033\n\025PKT_REQ_ACC_UPDATE_ID\020\371\233=\022\033\n\025"
  "PKT_REQ_ACC_UPDATE_PW\020\372\233=\022\035\n\027PKT_REQ_ACC"
  "_UPDATE_AUTH\020\373\233=\022\034\n\026PKT_REQ_CNN_LOBBY_SE"
  "RV\020\341\243=\022\033\n\025PKT_REQ_CNN_GAME_SERV\020\342\243=\022\033\n\025P"
  "KT_REQ_CNN_CHAT_SERV\020\343\243=\022\032\n\024PKT_REQ_DC_A"
  "UTH_SERV\020\311\253=\022\033\n\025PKT_REQ_DC_LOBBY_SERV\020\312\253"
  "=\022\032\n\024PKT_REQ_DC_GAME_SERV\020\313\253=\022\032\n\024PKT_REQ"
  "_DC_CHAT_SERV\020\314\253=\022\034\n\026PKT_FAIL_LOGIN_UNKN"
  "OWN\020\311\231C\022\035\n\027PKT_FAIL_LOGIN_INV_MAIL\020\312\231C\022\033"
  "\n\025PKT_FAIL_LOGIN_INV_ID\020\313\231C\022\033\n\025PKT_FAIL_"
  "LOGIN_INV_PW\020\314\231C\022\030\n\022PKT_FAIL_LOGIN_BAN\020\315"
  "\231C\022\036\n\030PKT_FAIL_SIGN_UP_UNKNOWN\020\261\241C\022\037\n\031PK"
  "T_FAIL_SIGN_UP_INV_MAIL\020\262\241C\022\037\n\031PKT_FAIL_"
  "SIGN_UP_MAIL_BAN\020\263\241C\022\035\n\027PKT_FAIL_SIGN_UP"
  "_DUP_ID\020\264\241C\022\035\n\027PKT_FAIL_SIGN_UP_INV_PW\020\265"
  "\241C\022\037\n\031PKT_FAIL_SIGN_UP_INV_AUTH\020\266\241C\022\034\n\026P"
  "KT_FAIL_ACC_UPDATE_ID\020\231\251C\022\034\n\026PKT_FAIL_AC"
  "C_UPDATE_PW\020\232\251C\022\036\n\030PKT_FAIL_ACC_UPDATE_A"
  "UTH\020\233\251C\022\034\n\026PKT_FAIL_CNN_AUTH_SERV\020\201\261C\022\035\n"
  "\027PKT_FAIL_CNN_LOBBY_SERV\020\202\261C\022\034\n\026PKT_FAIL"
  "_CNN_GAME_SERV\020\203\261C\022\034\n\026PKT_FAIL_CNN_CHAT_"
  "SERV\020\204\261C\022\023\n\rPKT_SUC_LOGIN\020\351\246I\022\025\n\017PKT_SUC"
  "_SIGN_UP\020\321\256I\022\030\n\022PKT_SUC_SIGN_UP_ID\020\322\256I\022\030"
  "\n\022PKT_SUC_SIGN_UP_PW\020\323\256I\022\032\n\024PKT_SUC_SIGN"
  "_UP_AUTH\020\324\256I\022\033\n\025PKT_SUC_ACC_UPDATE_ID\020\271\266"
  "I\022\033\n\025PKT_SUC_ACC_UPDATE_PW\020\272\266I*\035\n\nERROR_"
  "CODE\022\017\n\013ERR_UNKNOWN\020\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Common_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Common_2eproto_sccs[1] = {
  &scc_info_LoginData_Common_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Common_2eproto_once;
static bool descriptor_table_Common_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Common_2eproto = {
  &descriptor_table_Common_2eproto_initialized, descriptor_table_protodef_Common_2eproto, "Common.proto", 1269,
  &descriptor_table_Common_2eproto_once, descriptor_table_Common_2eproto_sccs, descriptor_table_Common_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_Common_2eproto::offsets,
  file_level_metadata_Common_2eproto, 1, file_level_enum_descriptors_Common_2eproto, file_level_service_descriptors_Common_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Common_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Common_2eproto), true);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PACKET_HEADER_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Common_2eproto);
  return file_level_enum_descriptors_Common_2eproto[0];
}
bool PACKET_HEADER_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 1001001:
    case 1002001:
    case 1002002:
    case 1003001:
    case 1003002:
    case 1003003:
    case 1004001:
    case 1004002:
    case 1004003:
    case 1005001:
    case 1005002:
    case 1005003:
    case 1005004:
    case 1101001:
    case 1101002:
    case 1101003:
    case 1101004:
    case 1101005:
    case 1102001:
    case 1102002:
    case 1102003:
    case 1102004:
    case 1102005:
    case 1102006:
    case 1103001:
    case 1103002:
    case 1103003:
    case 1104001:
    case 1104002:
    case 1104003:
    case 1104004:
    case 1201001:
    case 1202001:
    case 1202002:
    case 1202003:
    case 1202004:
    case 1203001:
    case 1203002:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ERROR_CODE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Common_2eproto);
  return file_level_enum_descriptors_Common_2eproto[1];
}
bool ERROR_CODE_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void LoginData::InitAsDefaultInstance() {
}
class LoginData::_Internal {
 public:
};

LoginData::LoginData()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Protocol.LoginData)
}
LoginData::LoginData(const LoginData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  mail_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_mail().empty()) {
    mail_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.mail_);
  }
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_id().empty()) {
    id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  password_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_password().empty()) {
    password_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.LoginData)
}

void LoginData::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LoginData_Common_2eproto.base);
  mail_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

LoginData::~LoginData() {
  // @@protoc_insertion_point(destructor:Protocol.LoginData)
  SharedDtor();
}

void LoginData::SharedDtor() {
  mail_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void LoginData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LoginData& LoginData::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LoginData_Common_2eproto.base);
  return *internal_default_instance();
}


void LoginData::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.LoginData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  mail_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* LoginData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string mail = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_mail();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Protocol.LoginData.mail"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Protocol.LoginData.id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string password = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_password();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Protocol.LoginData.password"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LoginData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.LoginData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string mail = 1;
  if (this->mail().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mail().data(), static_cast<int>(this->_internal_mail().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.LoginData.mail");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_mail(), target);
  }

  // string id = 2;
  if (this->id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.LoginData.id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_id(), target);
  }

  // string password = 3;
  if (this->password().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_password().data(), static_cast<int>(this->_internal_password().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.LoginData.password");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_password(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.LoginData)
  return target;
}

size_t LoginData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.LoginData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string mail = 1;
  if (this->mail().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mail());
  }

  // string id = 2;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // string password = 3;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_password());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LoginData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Protocol.LoginData)
  GOOGLE_DCHECK_NE(&from, this);
  const LoginData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LoginData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Protocol.LoginData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Protocol.LoginData)
    MergeFrom(*source);
  }
}

void LoginData::MergeFrom(const LoginData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Protocol.LoginData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.mail().size() > 0) {

    mail_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.mail_);
  }
  if (from.id().size() > 0) {

    id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
}

void LoginData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Protocol.LoginData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginData::CopyFrom(const LoginData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.LoginData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginData::IsInitialized() const {
  return true;
}

void LoginData::InternalSwap(LoginData* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  mail_.Swap(&other->mail_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  id_.Swap(&other->id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_.Swap(&other->password_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata LoginData::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::LoginData* Arena::CreateMaybeMessage< ::Protocol::LoginData >(Arena* arena) {
  return Arena::CreateInternal< ::Protocol::LoginData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
